#!/usr/bin/env python3
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[2]
TODAY='2026-09-17'
def read(rel): return json.loads((ROOT/rel).read_text())
def write(rel,v):
 p=ROOT/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def ref(i,t,title,pub,url,note,authors=None,year=None,vol=None,issue=None,pages=None,doi=None,lic=None,cite=None):
 return {'reference_id':i,'source_type':t,'title':title,'authors':authors or [],'publisher_or_container':pub,'year':year,'volume':vol,'issue':issue,'pages':pages,'doi':doi,'isbn':None,'url':url,'accessed_at':TODAY,'license':lic,'rights_note':note,'citation_display':cite or f'{pub}. {title}.'}
def review(status,summary,ids): return {'status':status,'summary':summary,'reference_ids':ids}
def comp(status,terms,diff,note,ids): return {'status':status,'near_terms':terms,'difference_note':diff,'verification_note':note,'reference_ids':ids}
def inv(i,role,tier='A'): return {'reference_id':i,'role':role,'quality_tier':tier}
def claim(n,text,ids,loc): return {'claim_id':f'CL-{n:03d}','claim':text,'reference_ids':ids,'evidence_locator':loc,'public_safe':True}

registry=read('content/approved/references.json')
new=[
ref('R0094','lexical','Geborgenheit','Duden','https://www.duden.de/rechtschreibung/Geborgenheit','Authoritative German lexical entry. Duden defines the noun through Geborgensein and links it with protection/security; public wording must be original synthesis.',cite='Duden. (n.d.). Geborgenheit.'),
ref('R0095','scholarly','The Psychology of Adolf Busemann or Making Sense of Geborgenheit','Integrative Psychological & Behavioral Science','https://pubmed.ncbi.nlm.nih.gov/39708258/','Peer-reviewed psychological discussion framing Geborgenheit as a sense of security and inner stability.',authors=['Enno von Fircks'],year=2024,cite='von Fircks, E. (2024). The Psychology of Adolf Busemann or Making Sense of Geborgenheit. Integrative Psychological & Behavioral Science.'),
ref('R0096','pronunciation','Geborgenheit — Duden pronunciation','Duden','https://www.duden.de/rechtschreibung/Geborgenheit','Duden IPA used for pronunciation research. Duden audio, if any, is not assumed reusable; product audio rights remain HOLD.',cite='Duden. (n.d.). Geborgenheit — Aussprache.'),
ref('R0097','lexical','Fernweh','Duden','https://www.duden.de/rechtschreibung/Fernweh','Authoritative German lexical entry defining longing for distance/faraway countries.',cite='Duden. (n.d.). Fernweh.'),
ref('R0098','scholarly','The Elements of Eco-Connection: A Cross-Cultural Lexical Enquiry','International Journal of Environmental Research and Public Health','https://pmc.ncbi.nlm.nih.gov/articles/PMC6950391/','Peer-reviewed cross-cultural lexical enquiry discusses Fernweh as longing/call of faraway places, including lands unknown.',year=2020,cite='The Elements of Eco-Connection: A Cross-Cultural Lexical Enquiry. (2020). International Journal of Environmental Research and Public Health.'),
ref('R0099','pronunciation','Fernweh — Duden pronunciation','Duden','https://www.duden.de/rechtschreibung/Fernweh','Duden IPA used for pronunciation research; product-safe audio rights not established.',cite='Duden. (n.d.). Fernweh — Aussprache.'),
ref('R0100','lexical','Weltschmerz','Duden','https://www.duden.de/rechtschreibung/Weltschmerz','Authoritative German lexical entry defining a painful/sad basic mood of suffering from the world and its inadequacy relative to wishes/expectations.',cite='Duden. (n.d.). Weltschmerz.'),
ref('R0101','scholarly','Weltschmerz: Pessimism in German Philosophy, 1860–1900 — Introduction','Oxford University Press','https://academic.oup.com/book/9821/chapter-abstract/157051615','Scholarly historical account describes Weltschmerz as weariness/sadness about life arising from awareness of evil and suffering, with historical usage boundaries.',authors=['Frederick C. Beiser'],year=2016,doi='10.1093/acprof:oso/9780198768715.003.0001',cite='Beiser, F. C. (2016). Introduction: The Problem of Pessimism. In Weltschmerz: Pessimism in German Philosophy, 1860–1900. Oxford University Press.'),
ref('R0102','pronunciation','Weltschmerz — Duden pronunciation','Duden','https://www.duden.de/rechtschreibung/Weltschmerz','Duden IPA used for pronunciation research; product-safe audio rights not established.',cite='Duden. (n.d.). Weltschmerz — Aussprache.'),
ref('R0103','lexical','切ない','デジタル大辞泉（小学館） via goo辞書','https://dictionary.goo.ne.jp/word/%E5%88%87%E3%81%AA%E3%81%84/','Japanese lexical source: core emotional sense involves sadness/longing with a chest-tightening, unbearable quality. Public wording must preserve sense boundaries.',cite='小学館. (n.d.). 切ない. デジタル大辞泉.'),
ref('R0104','scholarly','Semantic Changes of the Emotional Adjective Setsunai in Modern Japanese','現代日本語研究 / Osaka University','https://ir.library.osaka-u.ac.jp/repo/ouka/all/61383/?lang=1','Term-specific semantic study; identifies empathy and ideal/expectation–reality gap as important features and documents modern meaning change.',authors=['Sasai Akari'],year=2017,vol='9',pages='60-75',doi='10.18910/61383',cite='Sasai, A. (2017). Semantic Changes of the Emotional Adjective Setsunai in Modern Japanese. 現代日本語研究, 9, 60–75.'),
ref('R0105','scholarly','Do momentary phenomena evoke mixed emotions?','Asian Journal of Social Psychology','https://onlinelibrary.wiley.com/doi/full/10.1111/ajsp.70043','Recent study discusses 切ない as a Japanese expression used for fragile/momentary phenomena and mixed emotion around endings; supports but does not prove exclusivity.',year=2025,doi='10.1111/ajsp.70043',cite='Shirai et al. (2025). Do momentary phenomena evoke mixed emotions? Asian Journal of Social Psychology.'),
ref('R0106','pronunciation','切ない — pronunciation','Wiktionary','https://en.wiktionary.org/wiki/%E5%88%87%E3%81%AA%E3%81%84','IPA and Tokyo pitch-accent provenance for research; no product audio is authorized by this reference.',lic='CC BY-SA 4.0 / site terms',cite='Wiktionary. (n.d.). 切ない.'),
ref('R0107','lexical','もどかしい','デジタル大辞泉（小学館） via goo辞書','https://dictionary.goo.ne.jp/word/%E3%82%82%E3%81%A9%E3%81%8B%E3%81%97%E3%81%84/','Japanese lexical source: irritation/impatience when things do not go as intended; public wording must preserve current sense boundary.',cite='小学館. (n.d.). もどかしい. デジタル大辞泉.'),
ref('R0108','scholarly','「じれったい、もどかしい、はがゆい」の意味分析','言葉と文化 / Nagoya University','https://nagoya.repo.nii.ac.jp/records/12229','Term-specific semantic analysis comparing じれったい, もどかしい, and はがゆい as emotion adjectives.',authors=['加藤恵梨'],year=2010,vol='11',pages='271-283',doi='10.18999/isslc.11.271',cite='加藤恵梨. (2010). 「じれったい、もどかしい、はがゆい」の意味分析. 言葉と文化, 11, 271–283.'),
ref('R0109','scholarly','Properties of Central and Peripheral Concepts of Emotion in Japanese and Korean: An Examination Using a Multi-Dimensional Model','Frontiers in Psychology','https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2022.825404/full','Cross-cultural emotion-concept study includes modokashii as a Japanese peripheral emotion concept translated as irritation and compares Japanese/Korean semantic organization.',year=2022,doi='10.3389/fpsyg.2022.825404',lic='CC BY',cite='Park et al. (2022). Properties of Central and Peripheral Concepts of Emotion in Japanese and Korean. Frontiers in Psychology, 13, 825404.'),
ref('R0110','pronunciation','もどかしい — pronunciation','Wiktionary','https://en.wiktionary.org/wiki/%E3%82%82%E3%81%A9%E3%81%8B%E3%81%97%E3%81%84','IPA and pitch-accent provenance for research; no product audio is authorized by this reference.',lic='CC BY-SA 4.0 / site terms',cite='Wiktionary. (n.d.). もどかしい.')]
m={x['reference_id']:x for x in registry['references']};m.update({x['reference_id']:x for x in new});registry['references']=[m[k] for k in sorted(m)];write('content/approved/references.json',registry)

configs={
'C0016':dict(term='Geborgenheit',lang='de-DE',name='Deutsch',etype='relational_experience',lex='R0094',sch=['R0095'],pron='R0096',ipa='[ɡəˈbɔrɡn̩haɪ̯t]',ko=['안전함','보호받는 느낌','포근함'],en=['security','shelteredness','emotional safety'],zh=['安全感','被保护的感觉','安心'],ja=['安心感','守られている感じ','安らぎ'],cost='EXPLANATORY_PHRASE_REQUIRED',render='누군가나 어떤 장소 안에서 안전하게 보호받고, 받아들여지고, 따뜻하게 품어져 있다고 느끼는 편안한 상태',dims=['physical safety','emotional security','warmth and closeness','acceptance and trust'],res='단순한 안전함보다 보호받음, 정서적 안정, 가까움과 온기, 신뢰와 수용이 한 상태 안에 함께 묶인다. 한국어에서는 보통 안전함·포근함·보호받는 느낌을 나누어 설명해야 이 결합을 보존할 수 있다.',over='독일어 화자만 느끼는 감정 또는 영어·한국어에 번역 불가능한 감정이라고 주장하지 않는다.'),
'C0017':dict(term='Fernweh',lang='de-DE',name='Deutsch',etype='feeling',lex='R0097',sch=['R0098'],pron='R0099',ipa='[ˈfɛrnveː]',ko=['먼 곳에 대한 그리움','여행 갈망'],en=['longing for faraway places','travel longing'],zh=['对远方的向往','远方乡愁'],ja=['遠くへの憧れ','旅への憧れ'],cost='SHORT_PHRASE_PARTIAL',render='멀리 있는 곳, 때로는 아직 가보지 않은 곳까지 향해 마음이 끌리고 그리워지는 느낌',dims=['longing directed toward distance','can target unknown places','not homesickness for a known home'],res='일반적인 여행 욕구보다 ‘먼 곳’을 향한 그리움이 중심이며, 이미 알고 있는 고향을 그리워하는 향수와 달리 가보지 않은 장소도 대상이 될 수 있다.',over='여행을 좋아하는 성향이나 wanderlust와 항상 동일하다고 축소하지 않는다.'),
'C0018':dict(term='Weltschmerz',lang='de-DE',name='Deutsch',etype='mood',lex='R0100',sch=['R0101'],pron='R0102',ipa='[ˈvɛltʃmɛrts]',ko=['세상에 대한 슬픔','세계의 불완전함에서 오는 괴로움'],en=['world-weariness','world pain'],zh=['对世界缺憾的悲痛','厌世式哀愁'],ja=['世界苦','世の不完全さへの悲哀'],cost='EXPLANATORY_PHRASE_REQUIRED',render='내가 바라는 이상과 실제 세계의 불완전함·고통 사이의 간극을 의식하며 느끼는 깊은 슬픔과 피로',dims=['pain about the world','ideal-reality gap','awareness of suffering or inadequacy','mood-like persistence'],res='단순한 우울·슬픔이 아니라 세계의 불완전함과 고통, 개인의 이상·기대 사이의 간극을 의식하는 데서 생기는 세계지향적 슬픔/피로라는 대상 구조가 포함된다.',over='임상적 우울증과 동일시하거나 현대 독일인의 보편적 성향으로 일반화하지 않는다.'),
'C0019':dict(term='切ない',lang='ja-JP',name='日本語',etype='mixed_experience',lex='R0103',sch=['R0104','R0105'],pron='R0106',ipa='[se̞t͡sɨna̠i]',ko=['애절하다','가슴이 아프다','그립고 슬프다'],en=['poignant','heart-rending','wistful and painful'],zh=['心酸','揪心','悲切'],ja=['悲しさや恋しさで胸が締め付けられる'],cost='EXPLANATORY_PHRASE_REQUIRED',render='슬픔이나 그리움 때문에 가슴이 조여 오는 듯 아프고, 마음대로 되지 않는 현실과 바람의 틈이 함께 느껴지는 상태',dims=['chest-tightening anguish','sadness or longing','empathy','ideal-expectation versus reality gap'],res='한국어의 애절하다·안타깝다·그립다와 각각 겹치지만, 슬픔/그리움의 신체적 조임과 기대-현실 간극, 타인/대상에 대한 감정이입이 한 어휘에서 함께 작동할 수 있다.',over='모든 현대 용례가 비극적이거나 연애 감정이라고 고정하지 않고, 의미 변화와 가벼운 현대 용법도 경계로 명시한다.'),
'C0020':dict(term='もどかしい',lang='ja-JP',name='日本語',etype='feeling',lex='R0107',sch=['R0108','R0109'],pron='R0110',ipa='[mo̞do̞ka̠ɕiː]',ko=['답답하다','애가 타다','뜻대로 안 돼 초조하다'],en=['frustrating','impatient','irritating'],zh=['着急','焦躁','不耐烦'],ja=['じれったい','はがゆい'],cost='SHORT_PHRASE_PARTIAL',render='원하는 대로 일이 되지 않거나 내가 바로 할 수 없어 답답하고 초조하게 애가 타는 느낌',dims=['blocked desired outcome','irritation at delay or inability','impatient urge for progress'],res='한국어 답답하다와 가깝지만 신체적/걱정 기반 답답함 전체가 아니라 원하는 진행이 막히거나 뜻대로 되지 않는 상황에서 생기는 조급한 자극감과 무능력감이 중심이다.',over='일반적인 분노·짜증 또는 성격적 성급함과 동일시하지 않는다.')}

def comparison(status,terms,diff,note,ids): return {'status':status,'near_terms':terms,'difference_note':diff,'verification_note':note,'reference_ids':ids}
for cid,c in configs.items():
 base=[c['lex'],*c['sch'],c['pron']]
 cost={'classification':c['cost'],'status':'PASS','nearest_korean_terms':c['ko'],'natural_korean_rendering':c['render'],'residue_dimensions':c['dims'],'reference_ids':[c['lex'],*c['sch']],'rationale':'가까운 한국어 표현을 제시해도 핵심 의미 요소가 분산되거나 일부가 남는다. 이 판단은 원어 사전 정의와 직접 관련 학술 연구의 의미 경계를 바탕으로 하며, 단순히 번역문을 길게 만들어 차이를 부풀린 것이 아니다.'}
 rr={'schema_version':'2.1.0','research_id':f'RR-{cid}-FOREIGN','card_id':cid,'candidate':{'term':c['term'],'language_code':c['lang'],'language_name':c['name'],'experience_type':c['etype']},'lifecycle_state':'HOLD','source_inventory':[inv(c['lex'],'lexical'),*([inv(x,'scholarly') for x in c['sch']]),inv(c['pron'],'pronunciation','B')],
 'lexical_verification':review('PASS','원어 사전에서 목표 표제어와 카드에 사용할 의미 범위를 확인했다.',[c['lex']]),
 'semantic_definition_and_boundaries':review('PASS',c['res'],[c['lex'],*c['sch']]),
 'cultural_context_review':review('PASS','어휘가 포착하는 의미 결은 설명하되 특정 문화 사람만 이 경험을 느낀다는 본질주의나 번역불가능성 주장을 하지 않는다.',[c['lex'],*c['sch']]),
 'comparisons':{
   'ko':comparison('PASS',c['ko'],'한국어 근접표현을 나열해도 원어가 한데 묶는 의미 요소 일부가 남는다.','Korean Expression Cost review is source-grounded.',[c['lex'],*c['sch']]),
   'en':comparison('HOLD',c['en'],'영어 근접어는 탐색용이며 독립 lexical verification을 추가해야 최종 비교가 PASS한다.','Provisional comparison only.',[c['lex']]),
   'zh':comparison('HOLD',c['zh'],'중국어 근접어는 탐색용이며 독립 lexical verification을 추가해야 최종 비교가 PASS한다.','Provisional comparison only.',[c['lex']]),
   'ja':comparison('PASS' if c['lang']=='ja-JP' else 'HOLD',c['ja'],'원어가 일본어인 경우 target lexical evidence로 자체 의미를 확인했고, 그렇지 않은 경우 일본어 근접어는 provisional이다.','Target-language evidence or provisional mapping as applicable.',[c['lex']])},
 'pronunciation_verification':{'status':'HOLD','ipa':c['ipa'],'locale':c['lang'],'reference_ids':[c['pron']],'audio_asset_id':None,'notes':'IPA/prosodic pronunciation provenance is recorded, but product-safe audio source, creator, locale fit, license, rights, and SHA linkage are not yet verified.'},
 'claim_source_map':[claim(1,c['res'],[c['lex'],*c['sch']],'Target lexical definition plus term-specific or directly relevant scholarly evidence.'),claim(2,'가까운 한국어 한 단어 하나만으로는 핵심 의미 패키지를 모두 보존하기 어렵다.',[c['lex'],*c['sch']],'Korean Expression Cost comparison against target semantic components.')],
 'relations':[],
 'illustration_brief':review('HOLD','Pronunciation/audio rights and full multilingual comparison are incomplete; illustration is deferred.',[c['lex']]),
 'editorial_copy':review('HOLD','Public poetic copy is deferred until all evidence, comparison, pronunciation, and rights gates can be evaluated together.',[c['lex'],*c['sch']]),
 'automated_gates':{'schema':'PASS','evidence':'PASS','pronunciation':'HOLD','cultural_humility':'PASS','rights':'HOLD','privacy':'PASS'},
 'distinctiveness_review':{'status':'PASS','track':'FOREIGN_KOREAN_GAP','generic_basic_emotion':False,'nearest_cross_language_terms':{'ko':c['ko'],'en':c['en'],'zh':c['zh'],'ja':c['ja']},'semantic_residue':c['res'],'residue_reference_ids':[c['lex'],*c['sch']],'overclaim_to_avoid':c['over'],'korean_expression_cost':cost},
 'human_editorial_release':{'status':'PENDING','reviewer':None,'reviewed_at':None,'notes':'Research-stage HOLD. Human Editorial Release is not open until audio rights and full KO/EN/ZH/JA comparison pass.'},
 'changelog':[{'date':TODAY,'state':'RESEARCH','note':'Foreign semantic-gap source-first research record created under v2.1 Korean Expression Cost contract.'},{'date':TODAY,'state':'HOLD','note':'Core lexical/scholarly distinctiveness passes; product audio rights and full multilingual comparison remain incomplete.'}]}
 write(f'content/g5/research-records/{cid}.json',rr)

snapshot={'schema_version':'1.0.0','batch_id':'G5-F01-FOREIGN-SEMANTIC-GAP','status':'RESEARCH_CORE_PASS_PRODUCT_GATES_HOLD','recorded_at':TODAY,'card_ids':list(configs),'terms':[c['term'] for c in configs.values()],'languages':sorted(set(c['name'] for c in configs.values())),'korean_expression_cost':{cid:c['cost'] for cid,c in configs.items()},'audio_rights':'HOLD_UNTIL_PRODUCT_SAFE_AUDIO_VERIFIED','full_multilingual_comparison':'HOLD_FOR_INDEPENDENT_EN_ZH_JA_LEXICAL_VERIFICATION','review_ready':0,'public_promotion_authorized':False,'notes':'First foreign-primary G5 research batch. 委屈 was intentionally not admitted because Korean 억울하다 may be too close; it remains a comparison candidate rather than being forced through.'}
write('content/g5/batches/01_foreign_semantic_gap_research.json',snapshot)
print(json.dumps({'status':'PASS','cards':list(configs),'refs':len(registry['references'])},ensure_ascii=False))
