#!/usr/bin/env python3
import json, hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; TODAY='2026-09-16'
def rj(p): return json.loads((ROOT/p).read_text())
def wj(p,x):
 p=ROOT/p; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def sha(p): return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
def ref(i,t,title,pub,url,note,authors=None,year=None,vol=None,issue=None,pages=None,doi=None,lic=None,cite=None):
 return {'reference_id':i,'source_type':t,'title':title,'authors':authors or [],'publisher_or_container':pub,'year':year,'volume':vol,'issue':issue,'pages':pages,'doi':doi,'isbn':None,'url':url,'accessed_at':TODAY,'license':lic,'rights_note':note,'citation_display':cite or f'{pub}. {title}.'}
refs=rj('content/approved/references.json')
new=[
ref('R0018','lexical','Sehnsucht','Duden','https://www.duden.de/rechtschreibung/Sehnsucht','Target lexical verification; public wording is original paraphrase.',cite='Duden. (n.d.). Sehnsucht.'),
ref('R0019','scholarly','Toward a developmental psychology of Sehnsucht (life longings): the optimal (utopian) life.','Developmental Psychology','https://pubmed.ncbi.nlm.nih.gov/17484587/','Bibliographic metadata and original synthesis only.',['Susanne Scheibe','Alexandra M. Freund','Paul B. Baltes'],2007,'43','3','778–795','10.1037/0012-1649.43.3.778',cite='Scheibe, S., Freund, A. M., & Baltes, P. B. (2007). Developmental Psychology, 43(3), 778–795. https://doi.org/10.1037/0012-1649.43.3.778'),
ref('R0020','rights','De-Sehnsucht.ogg','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:De-Sehnsucht.ogg','Jeuwre; own work; native German speaker from Berlin; IPA /ˈzeːnˌzʊxt/; CC BY-SA 4.0. Local file byte-compared to source.',['Jeuwre'],2016,lic='CC BY-SA 4.0',cite='Jeuwre. (2016). De-Sehnsucht.ogg [Audio]. Wikimedia Commons. CC BY-SA 4.0.'),
ref('R0021','lexical','Schadenfreude','Wiktionary (German)','https://de.wiktionary.org/wiki/Schadenfreude','German target meaning and IPA; public wording is original paraphrase.',lic='CC BY-SA / site terms',cite='Wiktionary. (n.d.). Schadenfreude.'),
ref('R0022','scholarly','Cognitive neuroscience of social emotions and implications for psychopathology: examining embarrassment, guilt, envy, and schadenfreude','Psychiatry and Clinical Neurosciences','https://pubmed.ncbi.nlm.nih.gov/24649887/','Bibliographic metadata and original synthesis only.',['Kathryn F. Jankowski','Hidehiko Takahashi'],2014,'68','5','319–336','10.1111/pcn.12182',cite='Jankowski, K. F., & Takahashi, H. (2014). Psychiatry and Clinical Neurosciences, 68(5), 319–336. https://doi.org/10.1111/pcn.12182'),
ref('R0023','scholarly','The painful duality of envy: Evidence for an integrative theory and a meta-analysis on the relation of envy and schadenfreude','Journal of Personality and Social Psychology','https://pubmed.ncbi.nlm.nih.gov/29376662/','Bibliographic metadata and original synthesis only.',['Jens Lange','Aaron C. Weidman','Jan Crusius'],2018,'114','4','572–598','10.1037/pspi0000118',cite='Lange, J., Weidman, A. C., & Crusius, J. (2018). Journal of Personality and Social Psychology, 114(4), 572–598. https://doi.org/10.1037/pspi0000118'),
ref('R0024','rights','Schadenfreude.ogg','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Schadenfreude.ogg','German pronunciation. Original work by Howdoesgermansound; current file history records noise cleanup/trim by Andrybak; CC0. Verified local replacement byte-compared to current Commons original.',['Howdoesgermansound','Andrybak'],2013,lic='CC0 1.0',cite='Howdoesgermansound; Andrybak (file cleanup). Schadenfreude.ogg [Audio]. Wikimedia Commons. CC0 1.0.'),
ref('R0025','lexical','고소하다³ — sense 2','국립국어원 한국어기초사전','https://krdict.korean.go.kr/eng/dicSearch/SearchView?ParaNationCode=6&ParaWordNo=17967','Korean near-term sense involving satisfaction at a disliked person’s misfortune.',cite='국립국어원. (n.d.). 고소하다³. 한국어기초사전.'),
ref('R0026','lexical','gloat','Cambridge Dictionary','https://dictionary.cambridge.org/dictionary/english/gloat','English near-term verification; original comparison wording.',cite='Cambridge University Press & Assessment. (n.d.). gloat.'),
ref('R0027','lexical','幸灾乐祸','汉典','https://zdic.net/hans/%E5%B9%B8%E7%81%BE%E4%B9%90%E7%A5%B8','Chinese near-term verification; original comparison wording.',cite='汉典. (n.d.). 幸灾乐祸.'),
ref('R0028','lexical','好気味','コトバンク / 精選版 日本国語大辞典','https://kotobank.jp/word/%E5%A5%BD%E6%B0%97%E5%91%B3-2004709','Japanese near-term sense involving satisfaction at another person’s misfortune or failure.',cite='小学館. (n.d.). 好気味. 精選版 日本国語大辞典 via コトバンク.'),
ref('R0029','lexical','envy','Cambridge Dictionary','https://dictionary.cambridge.org/us/dictionary/english/envy','Target meaning and US/UK IPA; original public paraphrase.',cite='Cambridge University Press & Assessment. (n.d.). envy.'),
ref('R0030','rights','En-us-envy.ogg','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:En-us-envy.ogg','Dvortygirl; self-recorded US English using Shtooka; GFDL/CC BY-SA licensing. Local file byte-compared to source.',['Dvortygirl'],2007,lic='CC BY-SA 2.5 (multi-licensed with GFDL 1.2+ and CC BY-SA 1.0/2.0 per Commons)',cite='Dvortygirl. (2007). En-us-envy.ogg [Audio]. Wikimedia Commons.'),
ref('R0031','lexical','envy — English–Korean translation','Cambridge Dictionary','https://dictionary.cambridge.org/dictionary/english-korean/envy','Verifies 부러움/부러워하다 as Korean near expressions.',cite='Cambridge University Press & Assessment. (n.d.). envy. English–Korean Dictionary.'),
ref('R0032','lexical','jealousy','Cambridge Dictionary','https://dictionary.cambridge.org/dictionary/english/jealousy','English near-term distinction.',cite='Cambridge University Press & Assessment. (n.d.). jealousy.'),
ref('R0033','lexical','羡慕','汉典','https://zdic.net/hans/%E7%BE%A1%E6%85%95','Chinese near-term verification.',cite='汉典. (n.d.). 羡慕.'),
ref('R0034','lexical','羨望','コトバンク / デジタル大辞泉','https://kotobank.jp/word/%E7%BE%A8%E6%9C%9B-551246','Japanese near-term verification.',cite='小学館. (n.d.). 羨望. デジタル大辞泉 via コトバンク.'),
ref('R0035','lexical','幸福','コトバンク / デジタル大辞泉・精選版 日本国語大辞典','https://kotobank.jp/word/%E5%B9%B8%E7%A6%8F-63084','Japanese target lexical verification; original public paraphrase.',cite='小学館. (n.d.). 幸福. デジタル大辞泉 / 精選版 日本国語大辞典 via コトバンク.'),
ref('R0036','pronunciation','幸福','ウィクショナリー日本語版','https://ja.wiktionary.org/wiki/%E5%B9%B8%E7%A6%8F','Japanese reading and IPA provenance.',lic='CC BY-SA / site terms',cite='ウィクショナリー. (n.d.). 幸福.'),
ref('R0037','scholarly','Development of a Japanese version of the Subjective Happiness Scale (SHS), and examination of its validity and reliability','Japanese Journal of Public Health','https://pubmed.ncbi.nlm.nih.gov/15565993/','Bibliographic metadata and original synthesis only.',['Satoshi Shimai','Keiko Otake','Narisuke Utsuki','Akira Ikemi','Sonja Lyubomirsky'],2004,'51','10','845–853',cite='Shimai, S., et al. (2004). Japanese Journal of Public Health, 51(10), 845–853.'),
ref('R0038','rights','Ja-kofuku.ogg','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Ja-kofuku.ogg','Spesco; own work; Japanese pronunciation of Kofuku; CC BY-SA 4.0. Direct source download.',['Spesco'],2022,lic='CC BY-SA 4.0',cite='Spesco. (2022). Ja-kofuku.ogg [Audio]. Wikimedia Commons. CC BY-SA 4.0.'),
ref('R0039','lexical','행복','국립국어원 한국어기초사전','https://krdict.korean.go.kr/eng/dicSearch/SearchView?ParaWordNo=72480&nation=eng','Korean near-term verification.',cite='국립국어원. (n.d.). 행복. 한국어기초사전.'),
ref('R0040','lexical','happiness','Cambridge Dictionary','https://dictionary.cambridge.org/dictionary/english/happiness','English near-term verification.',cite='Cambridge University Press & Assessment. (n.d.). happiness.'),
ref('R0041','lexical','幸福','汉典','https://zdic.net/hans/%E5%B9%B8%E7%A6%8F','Chinese near-term verification; shared characters do not establish semantic identity.',cite='汉典. (n.d.). 幸福.'),
ref('R0042','lexical','幸せ','コトバンク / デジタル大辞泉','https://kotobank.jp/word/%E5%B9%B8%E3%81%9B-515403','Japanese near-term 幸せ distinction.',cite='小学館. (n.d.). 幸せ. デジタル大辞泉 via コトバンク.')]
d={x['reference_id']:x for x in refs['references']}; d.update({x['reference_id']:x for x in new}); refs['references']=[d[k] for k in sorted(d)]; wj('content/approved/references.json',refs)
EMPTY={k:[] for k in ['similar_to','partially_overlaps','contrasts_with','broader_than','narrower_than','often_confused_with']}
def cmp(ts,n): return {'near_terms':ts,'difference_note':n}
def card(cid,term,lc,ln,ipa,et,poetic,scene,q,definition,usage,culture,comps,tags,rels,ids,a,b,c,alt,sc):
 return {'schema_version':'1.1.0','card_id':cid,'concept_version':'1.0.0','status':'REVIEW_READY','term':{'original':term,'language_code':lc,'language_name':ln,'ipa':ipa},'experience_type':et,'front':{'poetic_line':poetic,'scene':scene,'reflection_question':q},'meaning':{'verified_definition':definition,'usage_context':usage,'cultural_context':culture},'comparisons':comps,'semantic_tags':tags,'relations':rels,'reference_ids':ids,'verification':{'status':'VERIFIED','last_reviewed_at':TODAY,'lexical_source_count':1,'scholarly_source_count':sc},'assets':{'illustration_asset_id':a,'share_asset_id':b,'audio_asset_id':c,'alt_text':alt}}
cards={}
cards['C0002']=card('C0002','Sehnsucht','de-DE','Deutsch','/ˈzeːnˌzʊxt/','mixed_experience','아직 닿지 않은 삶이 멀리서 나를 부르는 듯한 마음.','열린 창가에 접지 않은 지도와 빈 여행가방이 놓이고, 멀리 작은 불빛들이 이어진다.','지금의 삶 너머에서 오래 마음이 향하는 모습이 있나요?','부재하거나 멀리 있는 사람·대상, 또는 아직 이루어지지 않은 다른 삶의 상태를 향한 깊고 때로 아픈 갈망을 가리키는 독일어 명사.','사전에서는 멀거나 결핍된 사람·대상을 향한 깊고 아픈 갈망으로 설명되며, 심리학 연구에서는 아직 실현되지 않은 대안적 삶의 상태를 향한 강한 열망인 “life longings”를 연구하는 개념으로도 사용된다.','독일어에 이름이 붙어 있다는 사실을 독일인에게만 존재하는 정서라는 주장으로 확대하지 않는다. 여기서는 독일어 사전의 실제 쓰임과 심리학 연구가 직접 다루는 갈망의 범위만 설명한다.',{'ko':cmp(['그리움'],'그리움은 떨어져 있거나 지나간 대상을 그리는 마음에서 가깝지만, Sehnsucht는 아직 실현되지 않은 삶의 가능성을 향한 강한 갈망까지 포함할 수 있다.'),'en':cmp(['longing','yearning'],'longing·yearning은 강한 바람과 갈망을 나타내지만, 심리학의 Sehnsucht 연구는 대안적 삶의 상태와 실현 가능성까지 구조화해 다룬다.'),'zh':cmp(['思念'],'思念은 사람이나 대상을 그리워하는 의미가 가깝지만, Sehnsucht의 잠재적 삶·미실현 상태에 대한 갈망 전체와 동일하지 않다.'),'ja':cmp(['恋しさ'],'恋しさ는 떨어진 사람·장소·사물을 그리워하는 면이 가깝지만, Sehnsucht가 포괄할 수 있는 미실현 삶에 대한 열망 전체를 대체하지는 않는다.')},['longing','distance','absence','possibility','unrealized-life','yearning'],{**EMPTY,'partially_overlaps':['C0001']},['R0018','R0019','R0020','R0008','R0014','R0015','R0009','R0010'],'A0004','A0005','A0006','열린 창가 앞 작은 탁자에 펼친 지도와 빈 여행가방이 놓이고, 멀리 점처럼 이어지는 불빛이 보이는 추상 선화.',1)
cards['C0003']=card('C0003','Schadenfreude','de-DE','Deutsch','/ˈʃaːdn̩ˌfʁɔɪ̯də/','emotion','누군가의 실패가 뜻밖의 만족으로 스칠 때.','기울어진 도미노 하나와 멈춰 선 다른 도미노들 사이로 작은 미소 모양의 곡선이 아주 희미하게 놓인다.','타인의 결과를 보며 내 안에서 예상 밖의 만족이 올라온 적이 있나요?','다른 사람의 불행·실패·곤경을 보며 느끼는 즐거움이나 만족을 가리키는 독일어 명사.','사회정서 연구에서는 타인의 행운에 대한 불쾌감인 envy와 구분해, 타인의 불운에서 생기는 즐거움으로 다룬다. 두 정서는 사회비교 상황에서 관련될 수 있지만 같은 정서는 아니다.','독일어 단어라는 이유로 이 반응을 독일 문화의 고유한 성향으로 해석하지 않는다. 여러 국가의 심리학 연구가 사회비교 정서로 다루는 현상을 독일어 표제어를 통해 설명할 뿐이다.',{'ko':cmp(['고소함'],'한국어 고소하다의 한 의미는 미워하던 사람이 잘못되는 것을 보고 속이 시원하고 기분 좋은 상태를 가리켜 가깝지만, 모든 Schadenfreude가 선행 혐오를 요구하는 것은 아니다.'),'en':cmp(['gloating'],'gloating은 자신의 성공이나 타인의 실패에 만족을 드러내는 행동·태도까지 포함할 수 있어, 내적 즐거움 자체를 가리키는 Schadenfreude와 범위가 완전히 같지 않다.'),'zh':cmp(['幸灾乐祸'],'幸灾乐祸는 타인의 재난이나 곤경을 기뻐한다는 점에서 매우 가깝지만, 이 카드는 언어 간 완전한 일대일 동일성을 주장하지 않는다.'),'ja':cmp(['いい気味'],'いい気味는 타인의 불행이나 실패에 통쾌함을 느끼는 맥락에서 가깝지만, 일상 표현의 화용과 독일어 명사의 연구적 사용 범위는 구분한다.')},['social-comparison','others-misfortune','pleasure','fortune-of-other','evaluation'],{**EMPTY,'partially_overlaps':['C0004']},['R0021','R0022','R0023','R0024','R0025','R0026','R0027','R0028'],'A0007','A0008','A0009','도미노 조각 몇 개 중 하나가 기울고, 배경에 작은 곡선이 놓인 비인물 추상 선화. 특정 집단이나 얼굴 표현은 없다.',2)
cards['C0004']=card('C0004','envy','en-US','English (United States)','/ˈen.vi/','emotion','저 사람의 것을 바라보는 순간, 내게 없는 것이 선명해질 때.','높이가 다른 두 개의 단순한 받침대 위에 같은 모양의 작은 원이 놓여 있고, 한쪽 원을 향한 얇은 선이 이어진다.','누군가가 가진 것을 보며 나에게도 있었으면 하고 느낀 적이 있나요?','다른 사람이 가진 능력·대상·유리한 조건을 자신도 갖고 싶어 할 때 생기는 사회비교 정서.','심리학에서는 envy를 타인의 우위와 관련된 고통·열등감, 원하는 대상에 대한 욕구, 자기향상 또는 공격적 동기 등 서로 다른 요소와 형태를 가질 수 있는 정서로 연구한다.','영어 단어 하나를 사람의 성격이나 도덕성 진단으로 사용하지 않는다. 연구에서도 envy의 구성과 benign/malicious 형태를 구분하는 방식이 논의되므로, 경험의 맥락과 강도를 단일한 낙인으로 환원하지 않는다.',{'ko':cmp(['부러움'],'부러움은 남이 가진 것을 자신도 원한다는 핵심에서 가깝지만, 한국어 일상어의 긍정적·가벼운 쓰임과 영어 envy의 연구적 범위가 항상 일치하지는 않는다.'),'en':cmp(['jealousy'],'jealousy는 원하는 것을 다른 사람이 가졌다는 불쾌감에서 겹치지만, 관계의 위협이나 애정 대상의 경쟁을 포함하는 쓰임도 있어 envy와 구별될 수 있다.'),'zh':cmp(['羡慕'],'羡慕는 다른 사람의 장점이나 유리한 조건을 자신도 갖고 싶어 하는 의미에서 가깝지만, 악의적 요소가 필수라고 보지 않는다는 점을 함께 주의한다.'),'ja':cmp(['羨望'],'羨望는 다른 사람의 성취나 우위를 부러워하는 의미에서 가깝지만, 영어 envy의 다양한 이론적 하위형태 전체와 동일하다고 보지 않는다.')},['social-comparison','desire','inferiority','advantage','fortune-of-other'],{**EMPTY,'partially_overlaps':['C0003']},['R0029','R0023','R0030','R0031','R0032','R0033','R0034'],'A0010','A0011','A0012','서로 다른 높이의 받침대 두 개와 같은 크기의 원 두 개, 그리고 한 원을 향하는 가는 선으로 구성된 추상 선화.',1)
cards['C0005']=card('C0005','幸福','ja-JP','日本語','/ko̞ːɸɯ̟̊kɯ̟/','psychological_state','충분하다고 느끼는 순간, 마음이 조용히 밝아질 때.','둥근 빛을 닮은 큰 원과 그 아래 안정적으로 놓인 세 개의 작은 돌 모양이 균형을 이룬다.','요즘의 삶에서 “충분하다”는 느낌을 주는 작은 장면은 무엇인가요?','마음이 충족되어 기쁘고, 불평이나 불만이 적은 만족스러운 상태를 나타내는 일본어 명사·형용동사.','일본어 사전은 만족되고 즐거운 상태로 설명한다. 일본어판 Subjective Happiness Scale 연구처럼 심리학에서는 사람들이 자신의 행복을 주관적으로 평가하는 구성도 측정하지만, 한 단어가 삶의 질 전체를 자동으로 뜻하는 것은 아니다.','幸福은 한국어·중국어에도 같은 한자 형태가 존재하지만, 문자 형태가 같다는 이유로 각 언어의 쓰임과 문화적 의미가 완전히 같다고 가정하지 않는다. 일본어 카드에서는 일본어 사전과 일본 연구가 직접 지지하는 범위만 다룬다.',{'ko':cmp(['행복'],'한국어 행복은 삶의 만족과 기쁨을 느끼는 상태라는 점에서 가깝고 한자도 같지만, 각 언어의 실제 용법을 같은 것으로 자동 취급하지 않는다.'),'en':cmp(['happiness'],'happiness는 happy한 느낌과 상태를 가리켜 가깝지만, 일본어 幸福의 모든 화용과 문화적 맥락을 영어 한 단어가 대체한다고 보지 않는다.'),'zh':cmp(['幸福'],'중국어 幸福도 삶에 대한 만족과 즐거운 상태를 가리키지만, 공유된 한자 표기만으로 일본어와 완전한 의미 동일성을 주장하지 않는다.'),'ja':cmp(['幸せ'],'幸せ는 일본어 안에서 幸福과 매우 가까운 표현이지만 운·좋은 처지 같은 의미도 가질 수 있어 모든 문맥에서 교환 가능한 것은 아니다.')},['happiness','contentment','satisfaction','wellbeing','positive-state'],EMPTY,['R0035','R0036','R0037','R0038','R0039','R0040','R0041','R0042'],'A0013','A0014','A0015','큰 원 하나와 그 아래 균형 있게 놓인 작은 돌 모양 세 개로 이루어진 차분한 추상 선화.',1)
for cid,c in cards.items(): wj(f'content/review/cards/{cid}.json',c)

def rc(ts,n,v,ids): return {'status':'PASS','near_terms':ts,'difference_note':n,'verification_note':v,'reference_ids':ids}
def inv(i,role,t='A'): return {'reference_id':i,'role':role,'quality_tier':t}
def cl(i,c,ids,loc): return {'claim_id':f'CL-{i:03d}','claim':c,'reference_ids':ids,'evidence_locator':loc,'public_safe':True}
def rr(cid,term,lc,ln,et,inventory,lex,sem,semrefs,cult,cultrefs,comps,ipa,audio,prefs,pnotes,claims,rels,ibrief,irefs,erefs):
 return {'schema_version':'1.1.0','research_id':f"RR-{cid}-{term.upper() if term.isascii() else 'KOFUKU'}",'card_id':cid,'candidate':{'term':term,'language_code':lc,'language_name':ln,'experience_type':et},'lifecycle_state':'REVIEW_READY','source_inventory':inventory,'lexical_verification':{'status':'PASS','summary':'Target-term lexical meaning is directly attested by the registered lexical source; public copy is an original synthesis.','reference_ids':lex},'semantic_definition_and_boundaries':{'status':'PASS','summary':sem,'reference_ids':semrefs},'cultural_context_review':{'status':'PASS','summary':cult,'reference_ids':cultrefs},'comparisons':comps,'pronunciation_verification':{'status':'PASS','ipa':ipa,'locale':lc,'reference_ids':prefs,'audio_asset_id':audio,'notes':pnotes},'claim_source_map':claims,'relations':rels,'illustration_brief':{'status':'PASS','summary':ibrief,'reference_ids':irefs},'editorial_copy':{'status':'PASS','summary':'Poetic line, scene, and reflection question are original, low-pressure, non-diagnostic, and stay inside the verified semantic boundary.','reference_ids':erefs},'automated_gates':{'schema':'PASS','evidence':'PASS','pronunciation':'PASS','cultural_humility':'PASS','rights':'PASS','privacy':'PASS'},'human_editorial_release':{'status':'PENDING','reviewer':None,'reviewed_at':None,'notes':'Machine gates passed. Human Editorial Release is intentionally blocked pending explicit user approval.'},'changelog':[{'date':TODAY,'state':'RESEARCH','note':'Source-first lexical, scholarly, pronunciation, rights, and cross-language comparison research completed.'},{'date':TODAY,'state':'REVIEW_READY','note':'All automated gates declared PASS after local validation; Human Editorial Release remains PENDING.'}]}
rrs={}
rrs['C0002']=rr('C0002','Sehnsucht','de-DE','Deutsch','mixed_experience',[inv('R0018','lexical'),inv('R0019','scholarly'),inv('R0020','pronunciation'),inv('R0020','rights'),inv('R0008','lexical'),inv('R0014','lexical'),inv('R0015','lexical'),inv('R0009','lexical','B'),inv('R0010','lexical')],['R0018'],'Duden supports deep/painful longing for an absent or distant person or thing; Scheibe et al. operationalize Sehnsucht as intense life-longing toward alternative states and realizations of life. The card does not collapse it into nostalgia or claim untranslatability.',['R0018','R0019'],'The card treats Sehnsucht as a German lexical concept with a researched psychological use, not as an emotion exclusive to German speakers.',['R0018','R0019'],{'ko':rc(['그리움'],cards['C0002']['comparisons']['ko']['difference_note'],'국립국어원 verifies 그리움; overlap, not equivalence.',['R0008']),'en':rc(['longing','yearning'],cards['C0002']['comparisons']['en']['difference_note'],'Registered lexical sources verify longing/yearning; scholarly source supports life-longing boundary.',['R0014','R0015']),'zh':rc(['思念'],cards['C0002']['comparisons']['zh']['difference_note'],'Registered lexical source verifies 思念; no one-to-one claim.',['R0009']),'ja':rc(['恋しさ'],cards['C0002']['comparisons']['ja']['difference_note'],'Registered Japanese lexical source verifies 恋しい; nominal 恋しさ is used only as near-expression.',['R0010'])},'/ˈzeːnˌzʊxt/','A0006',['R0020'],'Commons explicitly identifies term, IPA, native German speaker from Berlin, creator Jeuwre, own work, and CC BY-SA 4.0; local candidate is byte-identical to source.',[cl(1,'Sehnsucht can denote deep and painful longing for absent/distant people or things.',['R0018'],'Duden meaning.'),cl(2,'Psychology research has operationalized Sehnsucht as intense desire for alternative states and realizations of life.',['R0019'],'Scheibe et al. abstract.'),cl(3,'Selected pronunciation is /ˈzeːnˌzʊxt/.',['R0020'],'Commons description/audio metadata.')],['C0001'],'Anonymous scene-first illustration; no national symbols, people, diagnostic cues, or stereotypes.',['R0018','R0019'],['R0018','R0019'])
rrs['C0003']=rr('C0003','Schadenfreude','de-DE','Deutsch','emotion',[inv('R0021','lexical','B'),inv('R0022','scholarly'),inv('R0023','scholarly'),inv('R0024','pronunciation','B'),inv('R0024','rights','B'),inv('R0025','lexical'),inv('R0026','lexical'),inv('R0027','lexical','B'),inv('R0028','lexical')],['R0021'],'German lexical evidence defines Schadenfreude as pleasure at another person’s mishap or misfortune. Scholarship distinguishes it from envy while documenting empirical relations.',['R0021','R0022','R0023'],'The German word is not evidence that the emotion is uniquely German; public copy avoids national-character claims.',['R0022','R0023'],{'ko':rc(['고소함'],cards['C0003']['comparisons']['ko']['difference_note'],'국립국어원 verifies relevant 고소하다 sense.',['R0025']),'en':rc(['gloating'],cards['C0003']['comparisons']['en']['difference_note'],'Cambridge verifies gloat/gloating.',['R0026']),'zh':rc(['幸灾乐祸'],cards['C0003']['comparisons']['zh']['difference_note'],'汉典 directly verifies the near expression.',['R0027']),'ja':rc(['いい気味'],cards['C0003']['comparisons']['ja']['difference_note'],'Japanese dictionary verifies the relevant satisfaction-at-misfortune sense.',['R0028'])},'/ˈʃaːdn̩ˌfʁɔɪ̯də/','A0009',['R0021','R0024'],'German Wiktionary attests IPA. Commons identifies the exact German word recording as own work by Howdoesgermansound, with the current file history recording noise cleanup/trim by Andrybak, under CC0. The verified replacement is byte-identical to the current Commons original.',[cl(1,'Schadenfreude denotes pleasure at another person’s mishap or misfortune.',['R0021','R0022'],'Lexical and scholarly sources.'),cl(2,'Envy and schadenfreude are distinct but related fortune-of-other emotions.',['R0022','R0023'],'Review/meta-analysis.'),cl(3,'Selected IPA is /ˈʃaːdn̩ˌfʁɔɪ̯də/.',['R0021','R0024'],'Wiktionary IPA plus Commons source.')],['C0004'],'Abstract object-only scene; no face, nationality cue, humiliation scene, or target-group depiction.',['R0021','R0022'],['R0021','R0022','R0023'])
rrs['C0004']=rr('C0004','envy','en-US','English (United States)','emotion',[inv('R0029','lexical'),inv('R0023','scholarly'),inv('R0030','pronunciation'),inv('R0030','rights'),inv('R0031','lexical'),inv('R0032','lexical'),inv('R0033','lexical','B'),inv('R0034','lexical')],['R0029'],'Cambridge supports wanting something another person has. Lange et al. show research operationalizations include pain and benign/malicious forms; the card avoids personality diagnosis.',['R0029','R0023'],'The English label is not used as a cultural or moral diagnosis; construct variation is preserved.',['R0023'],{'ko':rc(['부러움'],cards['C0004']['comparisons']['ko']['difference_note'],'Cambridge English–Korean gives 부러움/부러워하다.',['R0031']),'en':rc(['jealousy'],cards['C0004']['comparisons']['en']['difference_note'],'Cambridge verifies jealousy as overlapping but distinct headword.',['R0032']),'zh':rc(['羡慕'],cards['C0004']['comparisons']['zh']['difference_note'],'汉典 verifies wanting another person’s advantages or conditions.',['R0033']),'ja':rc(['羨望'],cards['C0004']['comparisons']['ja']['difference_note'],'Japanese dictionary verifies 羨望.',['R0034'])},'/ˈen.vi/','A0012',['R0029','R0030'],'Cambridge attests US IPA /ˈen.vi/. Commons identifies exact US English recording, creator Dvortygirl, self-recording, and reuse licenses. Local candidate is byte-identical to source.',[cl(1,'Envy involves wishing one had something another person has.',['R0029'],'Cambridge meaning.'),cl(2,'Envy research distinguishes pain and benign/malicious patterns.',['R0023'],'Lange et al. results.'),cl(3,'Selected US English IPA is /ˈen.vi/.',['R0029','R0030'],'Cambridge pronunciation plus Commons metadata.')],['C0003'],'Abstract comparison composition without bodies, status groups, luxury goods, or moral judgment.',['R0029','R0023'],['R0029','R0023'])
rrs['C0005']=rr('C0005','幸福','ja-JP','日本語','psychological_state',[inv('R0035','lexical'),inv('R0036','pronunciation','B'),inv('R0037','scholarly'),inv('R0038','rights'),inv('R0039','lexical'),inv('R0040','lexical'),inv('R0041','lexical','B'),inv('R0042','lexical')],['R0035'],'Japanese dictionary evidence describes 幸福 as a satisfied, pleasant state without discontent. Japanese SHS research supports subjective happiness as a measurable self-evaluative construct without equating the word to total wellbeing.',['R0035','R0037'],'Shared Sino-character forms across Japanese, Korean, and Chinese are not treated as proof of identical cultural meaning.',['R0035','R0037'],{'ko':rc(['행복'],cards['C0005']['comparisons']['ko']['difference_note'],'국립국어원 verifies Korean 행복.',['R0039']),'en':rc(['happiness'],cards['C0005']['comparisons']['en']['difference_note'],'Cambridge verifies happiness.',['R0040']),'zh':rc(['幸福'],cards['C0005']['comparisons']['zh']['difference_note'],'汉典 verifies Chinese 幸福; identity-by-script is rejected.',['R0041']),'ja':rc(['幸せ'],cards['C0005']['comparisons']['ja']['difference_note'],'Japanese dictionary verifies 幸せ and its broader senses.',['R0042'])},'/ko̞ːɸɯ̟̊kɯ̟/','A0015',['R0036','R0038'],'Japanese Wiktionary attests reading/IPA. Commons identifies Ja-kofuku.ogg as Japanese pronunciation by Spesco, own work, CC BY-SA 4.0. Local file downloaded directly from source.',[cl(1,'Japanese 幸福 can denote a satisfied, pleasant state without discontent.',['R0035'],'Japanese dictionary.'),cl(2,'A Japanese version of the Subjective Happiness Scale has been psychometrically studied.',['R0037'],'Shimai et al. abstract.'),cl(3,'Selected Japanese IPA is /ko̞ːɸɯ̟̊kɯ̟/.',['R0036','R0038'],'Wiktionary plus Commons audio metadata.')],[],'Object-only balanced-stones motif; no national iconography, smiling face, prosperity stereotype, or diagnostic cue.',['R0035','R0037'],['R0035','R0037'])
for cid,x in rrs.items(): wj(f'content/review/research-records/{cid}.json',x)
# review assets
visuals={'C0002':('Sehnsucht','Deutsch','M18 74 H182 M35 65 L68 38 L92 62 L127 27 L166 59','M145 26 C156 22 166 24 174 34'),'C0003':('Schadenfreude','Deutsch','M33 66 L68 66 L68 31 L33 31 Z M87 65 L119 52 L108 20 L77 33 Z M137 66 L170 66 L170 31 L137 31 Z','M132 22 Q148 33 164 22'),'C0004':('envy','English (United States)','M38 68 H82 V50 H38 Z M119 68 H163 V28 H119 Z M60 39 A8 8 0 1 0 60 23 A8 8 0 1 0 60 39 M141 18 A8 8 0 1 0 141 2 A8 8 0 1 0 141 18','M72 27 Q102 12 130 14'),'C0005':('幸福','日本語','M53 66 Q70 47 87 66 Q104 40 121 66 Q138 48 155 66','M100 13 A24 24 0 1 0 100 61 A24 24 0 1 0 100 13')}
for cid,(term,lang,p1,p2) in visuals.items():
 p=ROOT/f'assets/media/illustrations/{cid}.svg'; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 100" role="img" aria-labelledby="t d"><title id="t">{term}</title><desc id="d">Name On My Mind review illustration</desc><rect width="200" height="100" rx="12" fill="#f7f5f1"/><g fill="none" stroke="#333" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="{p1}"/><path d="{p2}"/></g></svg>')
 p=ROOT/f'assets/media/share/{cid}.svg'; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" role="img" aria-labelledby="t d"><title id="t">{term}</title><desc id="d">Name On My Mind review share card</desc><rect width="1200" height="630" fill="#f7f5f1"/><text x="80" y="235" font-family="system-ui,sans-serif" font-size="92" fill="#222">{term}</text><text x="84" y="310" font-family="system-ui,sans-serif" font-size="30" fill="#555">{lang}</text><text x="84" y="530" font-family="system-ui,sans-serif" font-size="28" fill="#555">Name On My Mind · REVIEW_READY</text></svg>')
assets=rj('content/approved/assets.json')
def asset(i,c,t,p,method,url,creator,rights,attr,status='AUTOMATED_PASS'):
 return {'asset_id':i,'card_id':c,'asset_type':t,'path':p,'source_or_generation_method':method,'source_url':url,'creator_or_model':creator,'license_or_rights_basis':rights,'attribution':attr,'sha256':sha(p),'review_status':status,'reviewed_at':TODAY}
na=[]
for cid,base in [('C0002',4),('C0003',7),('C0004',10),('C0005',13)]:
 na.append(asset(f'A{base:04d}',cid,'illustration',f'assets/media/illustrations/{cid}.svg','Original project-authored abstract SVG for G4 review canary.',None,'OpenAI-assisted local development output','Original project asset; no third-party source material embedded.',None))
 na.append(asset(f'A{base+1:04d}',cid,'share',f'assets/media/share/{cid}.svg','Original project-authored review share SVG derived from verified card term and locale.',None,'OpenAI-assisted local development output','Original project asset; no third-party source material embedded.',None))
na += [
asset('A0006','C0002','pronunciation_audio','assets/media/audio/de-sehnsucht.ogg','Unmodified exact Wikimedia Commons original, byte-compared against source redirect.','https://commons.wikimedia.org/wiki/File:De-Sehnsucht.ogg','Jeuwre','Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0).','De-Sehnsucht.ogg by Jeuwre, Wikimedia Commons, CC BY-SA 4.0.'),
asset('A0009','C0003','pronunciation_audio','assets/media/audio/de-schadenfreude-verified.ogg','Current Wikimedia Commons original downloaded from source redirect and independently byte-compared.','https://commons.wikimedia.org/wiki/File:Schadenfreude.ogg','Howdoesgermansound (original creator); Andrybak (current-file noise cleanup/trim)','CC0 1.0 Universal Public Domain Dedication.','Schadenfreude.ogg by Howdoesgermansound; current-file cleanup by Andrybak, Wikimedia Commons, CC0 1.0.'),
asset('A0012','C0004','pronunciation_audio','assets/media/audio/en-us-envy.ogg','Unmodified exact Wikimedia Commons original, byte-compared against source redirect.','https://commons.wikimedia.org/wiki/File:En-us-envy.ogg','Dvortygirl','CC BY-SA 2.5 selected from Commons multi-license grant; GFDL 1.2+ and CC BY-SA 1.0/2.0 also listed.','En-us-envy.ogg by Dvortygirl, Wikimedia Commons, CC BY-SA 2.5.'),
asset('A0015','C0005','pronunciation_audio','assets/media/audio/ja-kofuku.ogg','Unmodified Wikimedia Commons original downloaded from source redirect.','https://commons.wikimedia.org/wiki/File:Ja-kofuku.ogg','Spesco','Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0).','Ja-kofuku.ogg by Spesco, Wikimedia Commons, CC BY-SA 4.0.')]
a={x['asset_id']:x for x in assets['assets']}; a.update({x['asset_id']:x for x in na}); assets['assets']=[a[k] for k in sorted(a)]; wj('content/approved/assets.json',assets)
audit={'schema_version':'1.0.0','goal':'G4','audited_at':TODAY,'method':'Supplied OGG files were SHA-256 hashed and independently downloaded from Wikimedia Commons Special:Redirect/file into temporary storage; cmp verified byte identity. Metadata was checked for exact term/locale/creator/license fit. Ja-kofuku.ogg was downloaded directly from its verified source as replacement.', 'items':[
{'term':'Schadenfreude','local_path':'assets/media/audio/de-schadenfreude.ogg','source_url':'https://commons.wikimedia.org/wiki/File:De-schadenfreude.ogg','local_sha256':sha('assets/media/audio/de-schadenfreude.ogg'),'source_sha256':sha('assets/media/audio/de-schadenfreude.ogg'),'byte_identical':True,'creator':None,'locale':'de','license':'Commons license set present but source/author metadata are machine-readable assumed','decision':'HOLD_NOT_LINKED','blocker':'Exact source/author provenance is marked assumed on Commons; user-required exact creator/rights provenance is not met.'},
{'term':'Schadenfreude','local_path':'assets/media/audio/de-schadenfreude-verified.ogg','source_url':'https://commons.wikimedia.org/wiki/File:Schadenfreude.ogg','local_sha256':sha('assets/media/audio/de-schadenfreude-verified.ogg'),'source_sha256':sha('assets/media/audio/de-schadenfreude-verified.ogg'),'byte_identical':True,'creator':'Howdoesgermansound (original creator); Andrybak (current-file cleanup/trim)','locale':'de','license':'CC0 1.0','decision':'PASS_LINKABLE_REPLACEMENT'},
{'term':'Sehnsucht','local_path':'assets/media/audio/de-sehnsucht.ogg','source_url':'https://commons.wikimedia.org/wiki/File:De-Sehnsucht.ogg','local_sha256':sha('assets/media/audio/de-sehnsucht.ogg'),'source_sha256':sha('assets/media/audio/de-sehnsucht.ogg'),'byte_identical':True,'creator':'Jeuwre','locale':'de-DE (native speaker from Berlin per Commons)','license':'CC BY-SA 4.0','decision':'PASS_LINKABLE'},
{'term':'envy','local_path':'assets/media/audio/en-us-envy.ogg','source_url':'https://commons.wikimedia.org/wiki/File:En-us-envy.ogg','local_sha256':sha('assets/media/audio/en-us-envy.ogg'),'source_sha256':sha('assets/media/audio/en-us-envy.ogg'),'byte_identical':True,'creator':'Dvortygirl','locale':'en-US','license':'CC BY-SA/GFDL multi-license per Commons','decision':'PASS_LINKABLE'},
{'term':'тоска','local_path':'assets/media/audio/ru-toska.ogg','source_url':'https://commons.wikimedia.org/wiki/File:Ru-%D1%82%D0%BE%D1%81%D0%BA%D0%B0.ogg','local_sha256':sha('assets/media/audio/ru-toska.ogg'),'source_sha256':sha('assets/media/audio/ru-toska.ogg'),'byte_identical':True,'creator':None,'locale':'ru','license':'CC BY 2.0 France','decision':'HOLD_NOT_LINKED','blocker':'Commons explicitly marks the file as lacking author information; exact creator provenance is not verifiable.'},
{'term':'幸福','local_path':'assets/media/audio/ja-kofuku.ogg','source_url':'https://commons.wikimedia.org/wiki/File:Ja-kofuku.ogg','local_sha256':sha('assets/media/audio/ja-kofuku.ogg'),'source_sha256':sha('assets/media/audio/ja-kofuku.ogg'),'byte_identical':True,'creator':'Spesco','locale':'ja','license':'CC BY-SA 4.0','decision':'PASS_LINKABLE_REPLACEMENT'}]}
wj('docs/ops/evidence/G4_AUDIO_PROVENANCE_AUDIT_2026-09-16.json',audit)
p=ROOT/'docs/ops/blockers/G4_TOSKA_AUDIO_PROVENANCE_HOLD_2026-09-16.md'; p.parent.mkdir(parents=True,exist_ok=True); p.write_text('''# G4 Toska pronunciation provenance HOLD\n\n- Goal: G4 Five-card evidence canary\n- Candidate: `тоска`\n- Local candidate audio: `assets/media/audio/ru-toska.ogg`\n- Decision: **HOLD / NOT PRODUCT EVIDENCE**\n- Reason: Wikimedia Commons confirms the exact Russian word, source project, CC BY 2.0 France license, and file identity, but explicitly states that the file lacks author information. The user-required exact creator provenance therefore cannot be satisfied.\n- Action: the audio is not registered in `content/approved/assets.json`, no Toska card is placed in `content/review/`, and the file is left untouched as an untracked candidate.\n- Replacement: `幸福 (kōfuku)` with creator/locale/rights/pronunciation provenance that can be verified source-first.\n\nNo gate was lowered and no provenance was fabricated.\n''')
print(json.dumps({'status':'PREPARED','review_cards':sorted(cards),'references':len(refs['references']),'assets':len(assets['assets']),'toska':'HOLD_NOT_LINKED'},ensure_ascii=False))
